name: CI

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install required packages
        run: |
          ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime 
          apt-get update && apt-get install -y git sudo curl
      - name: ubuntu-install
        run: ./install.sh
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: macos-install
        run: ./install.sh
