[tools]
node = "lts"
rust = "latest"
python = "3.12"
go = "latest"
deno = "latest"
neovim = "latest"
lazygit = "latest"
lazydocker = "latest"
zellij = "latest"
usage = "latest"

[settings]
lockfile = true
