[tools]
node = "lts"
rust = "latest"
python = "3.12"
go = "latest"
deno = "latest"
"aqua:neovim/neovim" = "latest"
lazygit = "latest"
lazydocker = "latest"
zellij = "latest"
usage = "latest"

[settings]
lockfile = true
